"""empty message

Revision ID: e98e626e89bb
Revises: 
Create Date: 2018-06-16 13:30:15.927433

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e98e626e89bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('html_body', sa.Text(), nullable=True))
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True))
    op.drop_column('posts', 'html_body')
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###
