"""empty message

Revision ID: fa4f0cb4fb2c
Revises: 3a84f97818e6
Create Date: 2018-06-11 21:27:09.546529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa4f0cb4fb2c'
down_revision = '3a84f97818e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('posts', 'tiemstamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tiemstamp', mysql.DATETIME(), nullable=True))
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###
